language: ruby
rvm:
  - 3.1.0
cache: bundler
before_install:
  - gem install bundler -v 2.2.31
  - bundler -v

install:
  - bundle _2.2.31_ install --binstubs=./bundler_stubs
addons:
  postgresql: "9.4"
